# Generated by Django 5.2 on 2025-04-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("solveproblem", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="translated_texts",
            new_name="translated_text",
        ),
    ]
